### ISSUE TITLE
Store  data in csv

### ISSUE THREAD

**Issue by bondarenkoi07** [roman656/Manul#1]
https://stackoverflow.com/questions/18757097/writing-data-into-csv-file-in-c-sharp прочитай и реализуй, БЫСТРА **[ДАННЫЕ УДАЛЕНЫ]**

**Comment by bondarenkoi07** [comment]
И добавь меня в контрибьюторы

**Comment by roman656** [comment]
Я сравню с json. И приму решение.

**Comment by roman656** [comment]
Был выбран json, по причине: In JSON, each object can have different fields, and the field order is not significant in JSON. In the CSV file, all the records should have the same fields, and they should be in the same order.
